$ANSIBLE_VAULT;1.1;AES256
66373961643865373965353535373433366439356637386237633866383831626431633838346139
3634343339323861323335363830303033383864353834380a373632313733643836303861636139
32363765623239386130336630336339386336376663333530356136373433343263346564303332
3234316162636136310a396632333764393730363936376564626564336366366263643937353162
63366633643733383863326364656135663236613961323536303736366331306132